//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynaWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynaWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not build a valid Uri for the request. Please double-check the WebClient baseUrl and the WebRequest resource..
        /// </summary>
        internal static string WebClientBuildUrlFailed {
            get {
                return ResourceManager.GetString("WebClientBuildUrlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for MaxRedirects cannot be negative or equal to zero..
        /// </summary>
        internal static string WebClientMaxRedirectsInvalidMessage {
            get {
                return ResourceManager.GetString("WebClientMaxRedirectsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided WebClient cannot be null..
        /// </summary>
        internal static string WebClientNullMessage {
            get {
                return ResourceManager.GetString("WebClientNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided request cannot be null..
        /// </summary>
        internal static string WebClientRequestNullMessage {
            get {
                return ResourceManager.GetString("WebClientRequestNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for Timeout cannot be negative or equal to zero..
        /// </summary>
        internal static string WebClientTimeoutInvalidMessage {
            get {
                return ResourceManager.GetString("WebClientTimeoutInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token cannot be null..
        /// </summary>
        internal static string WebClientTokenNullMessage {
            get {
                return ResourceManager.GetString("WebClientTokenNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base URL for the client cannot be null..
        /// </summary>
        internal static string WebClientUrlNullMessage {
            get {
                return ResourceManager.GetString("WebClientUrlNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UserAgent provided cannot be null..
        /// </summary>
        internal static string WebClientUserAgentNullMessage {
            get {
                return ResourceManager.GetString("WebClientUserAgentNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file provided could not be read..
        /// </summary>
        internal static string WebIOFileNotRead {
            get {
                return ResourceManager.GetString("WebIOFileNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied JSON token is not valid..
        /// </summary>
        internal static string WebJsonTokenInvalidMessage {
            get {
                return ResourceManager.GetString("WebJsonTokenInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource/endpoint provided cannot be null..
        /// </summary>
        internal static string WebRequestEndpointNullMessage {
            get {
                return ResourceManager.GetString("WebRequestEndpointNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided WebRequest cannot be null..
        /// </summary>
        internal static string WebRequestNullMessage {
            get {
                return ResourceManager.GetString("WebRequestNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter provided cannot be null..
        /// </summary>
        internal static string WebRequestParameterNullMessage {
            get {
                return ResourceManager.GetString("WebRequestParameterNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WebRequestPortDataResultToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataResultToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WebRequestPortDataUrlToolTip {
            get {
                return ResourceManager.GetString("WebRequestPortDataUrlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web request timed out and did not complete. Data may or may not have reached the remote server..
        /// </summary>
        internal static string WebRequestTimedOutMessage {
            get {
                return ResourceManager.GetString("WebRequestTimedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web request was aborted before it could be completed. Data may or may not have reached the remote server..
        /// </summary>
        internal static string WebResponseAbortedMessage {
            get {
                return ResourceManager.GetString("WebResponseAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network transport error occured. Possible causes include network is down, failed DNS lookup, etc. This also means the request did not reach the intended recipient..
        /// </summary>
        internal static string WebResponseNetworkErrorMessage {
            get {
                return ResourceManager.GetString("WebResponseNetworkErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web request did not return a valid response status..
        /// </summary>
        internal static string WebResponseNoneMessage {
            get {
                return ResourceManager.GetString("WebResponseNoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL provided is not a valid URL..
        /// </summary>
        internal static string WebUrlInvalidMessage {
            get {
                return ResourceManager.GetString("WebUrlInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI is file or is UNC pointing to internal network.
        /// </summary>
        internal static string WebUrlIsLocal {
            get {
                return ResourceManager.GetString("WebUrlIsLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL cannot be null..
        /// </summary>
        internal static string WebUrlNullMessage {
            get {
                return ResourceManager.GetString("WebUrlNullMessage", resourceCulture);
            }
        }
    }
}
